### PR TITLE
Add vertex-colors example + Update material shader for USE_VERTEX_COLORS and USE_INSTANCED_COLOR

### PR DESCRIPTION
**Pull request by dmnsgn**
Fixes https://github.com/pex-gl/pex-renderer/issues/41 https://github.com/pex-gl/pex-renderer/issues/129
* [X] Add vertex color example showing a cube's uvs
* [X] Make sure passing either `aVertexColor` or `aColor` works
* [X] Add `aVertexColor * aColor);` for when both are specified (really edgy case)
* [X] Fix missing `defined(USE_INSTANCED_COLOR)` in `vec3 tint = decode(vColor, 3).rgb;` when using `USE_UNLIT_WORKFLOW`
* [X] Change default material color to white
* [X] Create a tint color chunk
* [X] Update material and depth passes
* [X] Add vertex color and instanced color alpha contribution to `data.opacity`

### CODE REVIEW

**Comment by dmnsgn** [comment]
I'd say moving everything to `getBaseColor` would centralise the behaviour.

**Comment by vorg** [comment]
Sounds good.

**Comment by vorg** [comment]
Then we can skip adding color in PBRData completely?

**Comment by dmnsgn** [comment]
Removed color from PBRData and added contribution to opacity in depth passes. Updated the comment above.

**Pull request merged**
