### PR TITLE
Add clear coat and refactor brdf/lighting

### LINKED ISSUE #17: Verify BRDF implementations in PBR.frag
There seem to be three in place...

### LINKED ISSUE #45: Add attenuation falloffs from KHR_lights
[KHR_lights ](https://github.com/UX3D-nopper/glTF/tree/master_lights_blinnphong/extensions/Khronos/KHR_lights) glTF extension.

### LINKED ISSUE #79: Implement clear coat
img_8708

https://google.github.io/filament//Materials.md.html#toc3.1.7

screen shot 2018-05-27 at 22 16 39
Found some old pbr shader doing this 
```
float GTR1(float NdotH, float a)
{
    if (a >= 1) return 1/PI;
    float a2 = a*a;
    float t = 1 + (a2-1)*NdotH*NdotH;
    return (a2-1) / (PI*log(a2)*t);
}

float smithG_GGX(float Ndotv, float alphaG)
{
    float a = alphaG*alphaG;
    float b = Ndotv*Ndotv;
    return 1/(Ndotv + sqrt(a + b - a*b));
}

`// clearcoat (ior = 1.5 -> F0 = 0.04)
    float Dr = GTR1(NdotH, mix(.1,.001,clearcoatGloss));
    float Fr = mix(.04, 1, FH);
    float Gr = smithG_GGX(NdotL, .25) * smithG_GGX(NdotV, .25);

result  += .25*clearcoat*Gr*Fr*Dr;
```

### PR DESCRIPTION
**Pull request by dmnsgn**
**Renderer**
Add define TARGET_MOBILE (used in brdf)
Add defines for clearCoat

**Material**
Add reflectance to material (default 0.5)
Add clearCoat parameters to material

**Lighting**
Use physically based lighting
Add direct chunk to centralise surface shading from lights
Refactor lights to use surface shading and ao directly
Add innerAngle to spotlight

**BRDF**
Refactor brdf for clearer FDG and clear coat brdf optimisation
Add clear-coat chunk to get brdf, recompute f0, get normals
Move normalPerturb into its own chunk to use it in both normal and clear coat normal calculation
Refactor indirect to use clear coat

**Material frag**
Make MIN_ROUGHNESS a define
Add data.f0 (Reflectance at normal incidence)
Rename alphaRoughness to linearRoughnes
Merge directDiffuse and directSpecular into directColor (see getSurfaceShading)
Add saturate function to chunk

Fix #79 
Fix #17 
Fix #45

### CODE REVIEW

**Comment by vorg** [comment]
Quick notes as i go:
- [ ] What's the source of `carbon-fiber.jpg`? add `carbon-fiber.txt` (preferred) or section in README
- [ ] `targetMobile`
	- [ ] document in readme
	- [ ] targetMobile is in renderer._state not renderer/this
	- [ ] before and after
- [ ] Add innerAngle to spotlight -> documentation, and set to 0
- [ ] "Add reflectance to material (default 0.5)" is that IOR? Default should be 0.25^2 => 0.25 * 0.16 = 0.04 (old value) -> documentation
- [ ] Compare old and new BRDF in materials example
- [ ] "Add clearCoat parameters to material" -> 0..1 documentation
- [ ] rename occlusion to illuminate
- [ ] "Refactor lights to use surface shading and ao directly" - AO only inpacts ambient i.e. indirect lighting. AO on directional lighting does look good visually but it's not technically correct and is redundant to shadows. Perhabs cavity map is the right thing to use here.
- [ ] how does indirect specular AO works?
- [ ] Has this improved? https://github.com/pex-gl/pex-renderer/issues/17

Other
- [ ] "Use physically based lighting" [units] evaluate and document
- [ ] evaluate falloffs for lights for KHR_Lights
- [ ] energyCompensation will come from multiscatters
- [ ] burley diffuse evaluate
- [ ] nullify emissiveColor by default?

**Comment by dmnsgn** [comment]
>  Compare old and new BRDF in materials example

Notable differences:
- Non disappearing highlights (roughness clamping)
- Achromatic edges (f0) 

preview

**Comment by dmnsgn** [comment]
> targetMobile  before and after

Notable differences:
- slightly darker shade on the rough grey balls

preview

**Comment by dmnsgn** [comment]
>  "Refactor lights to use surface shading and ao directly" - AO only inpacts ambient i.e. indirect lighting. AO on directional lighting does look good visually but it's not technically correct and is redundant to shadows. Perhabs cavity map is the right thing to use here.

AO has been kept as is, impacting indirect lighting:
- reflection probes
- area lights
- ambient light

>  how does indirect specular AO works?

See https://seblagarde.files.wordpress.com/2015/07/course_notes_moving_frostbite_to_pbr_v32.pdf#page=78. In short, it is not physically based but provides pleasant results and prevent artefacts.

**Comment by dmnsgn** [comment]
>  Has this improved? #17

@vorg would be nice to merge this first in order to test the brdf with the same skybox orientation in pbr-compare: https://github.com/pex-gl/pex-renderer/pull/162

**Pull request merged**
