### PR TITLE
Add texture transform support

### LINKED ISSUE #116: Enhanced texCoord support
### 1. Tex coords scale and offset

Useful for texturing floors (scale) or using sprite sheets (scale + offset)

```glsl
uniform float uTexCoord0Scale;
uniform vec2 uTexCoord0Offset;
```

### 2.Multiple tex coords support

Useful for lightmaps. It would also require a way to assigning given texture to given texture coords attribute.

```glsl
attribute vec2 texCoord0;
attribute vec2 texCoord1;
```

- [x] Q: How is glTF dealing with it?

### LINKED ISSUE #176: [gltf] Lack of KHR_texture_transform causing TextureTransformTest to fail in gltf.js
image

Expected:
image

https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/TextureTransformTest

KHR texture transform docs:
https://github.com/KhronosGroup/glTF/blob/65fabf38a23527ebedefa301487088346eee2a9b/extensions/2.0/Khronos/KHR_texture_transform/README.md

### PR DESCRIPTION
**Pull request by dmnsgn**
Feature:
- Refactor how to get pex-material texture to allow more opts and handle extensions in gltf-build
- Add a check for `extensionsRequired` (should this throw an error because that means we don't support a specific extension)
- Update material component set function to compute the texCoord transform on the CPU (and add a `texCoordTransformMatrix` to the material map) because transform are per texture AND per material. Matrix computed in the material to avoid overhead computation in the shader.
- Push a flag `#define USE_NAME_MAP_TEX_COORD_TRANSFORM` when `texCoordTransformMatrix` is found in the map: we don't wan't to send a useless uniform if there is no texCoord transform required
- Send a `uNameMapTexCoordTransform` uniform  when texCoordTransformMatrix is found in the map
- Update `getTextureCoordinates` in shader to handle both case: with and without texCoord transform uniform
- Handle for each map the check of the `#define USE_NAME_MAP_TEX_COORD_TRANSFORM` 

Fix #116
Fix #176

### CODE REVIEW

**Comment by dmnsgn** [comment]
@vorg am I clear to merge this one? It would help for finishing some bits and bobs on gltf-build file.

**Comment by vorg** [comment]
Let me have a look at it today.

**Comment by vorg** [comment]
Looks good. We really reaching Pro Engine DEFINE madness here :) Next level is generated code for all maps..

**Comment by dmnsgn** [comment]
I prefer to be really explicit with our defines :)

**Pull request merged**
