### PR TITLE
Post processing bloom

### PR DESCRIPTION
**Pull request by dmnsgn**
- [X] Port bloom shader with downsampling
- [X] Update post-processing components bloom pass and add downsample passes
- [X] Update bloom call in `index.js`
- [ ] Check threshold works (pex-renderer one different from tech garden)
- [x] Check examples for artefacts and changes in intensity (mainly brdf, materials and post-pro)
- [x] Check at different resolutions

Fix https://github.com/pex-gl/pex-renderer/issues/52

### CODE REVIEW

**Comment by dmnsgn** [comment]
@vorg Is there anything else we should double check when implementing this?

**Comment by simonharrisco** [comment]
4k:
4k

1080p:
1080p

720p:
720p

Its hard to tell what is because of the lower resolution. but it looks good

**Comment by vorg** [comment]
Resolution independence was the biggest issue from what i remember. Will review this branch before merging.

**Comment by vorg** [comment]
One connected issue with threshold is are we booming everything vs emissive only. Also what is threshold 1.5? Yes color value but in lunes? Some radiance? Pre/post exposure? Pre/post gamma?

This needs thought and documentation. Also connected: new BRDF and lighting models after we aligned with Filament (also pending review).

**Comment by vorg** [comment]
> One connected issue with threshold is are we booming everything vs emissive only

Actually we are not https://github.com/pex-gl/pex-renderer/blob/post-processing-bloom/shaders/post-processing/threshold.frag.js#L33

Setting `bloomTreshold` to hight value will result in only emissive blooming.

**Pull request merged**
