### PR TITLE
Add Rollup with UMD/ESM/CJS bundles + Update codebase with lebab

### PR DESCRIPTION
**Pull request by dmnsgn**
- [X] Add Rollup for CJS/UMD/ESM build
- [X] Use classes
- [X] Use es modules
- [X] Add prettier
- [x] Check `const log = require('debug')`
- [X] Use top-level packages (eg `import { vec3 } from pex-math` and not from `pex-math/vec3`)

### CODE REVIEW

**Comment by vorg** [comment]
From Slack by Damien:

> The more I was removing glslify, the less it made sense. There's 69 occurrences of `#pragma glslify` and some other pex-gl packages use it as well.
So I am not sure it's the best to switch to ES6 string literal just yet.

> Then my reasoning was: this should work if you have a webpack project but also not break the CJS/browserify workflow. The most straightforward tool to do that is Rollup. Nick told me you guys were using already a bunch of ES6 features (let/const, arrow functions, string literal, classes) notably in pex-nodes so I suggested moving forward for pex-renderer as well.

**Comment by vorg** [comment]
Comments: 
- as for Prettier, we use [Standard](http://standardjs.com)
- there are some spaces missing, semicolons, not sure if that lebabl leftovers
- you mentioned issues with `debug` module, what are they?
- how Rollup compares to Webpack?

**Comment by nicknikolov** [comment]
I think Prettier can be used with Standard together

**Comment by vorg** [comment]
```{
  "name": "pex-renderer",
  "version": "3.0.0-4",
  "description": "Physically Based Renderer for Pex",
  "main": "dist/pex-renderer.cjs.js",
  "module": "dist/pex-renderer.esm.js",
  "browser": "dist/pex-renderer.umd.js",
```

**Comment by dmnsgn** [comment]
* Standard + Prettier: https://github.com/sheerun/prettier-standard . Will add it.
* there are some spaces missing, semicolons: once prettier-standard is added, we'll able to format automatically and remove the leftovers
* Running into: https://github.com/visionmedia/debug/issues/511 and general uniformisation as there are more console.log in the rest of the codebase

Rollup:
* rules of thumb is: use webpack for apps, use rollup for libs
* easier to understand what's going on in the config file
* better if only a few asset types is used (here only js and text files for glsl)

**Comment by vorg** [comment]
@dmnsgn can we also add basic-mjs example based on basic example that is using es6 module import? Do we need to update pex context for that?

**Comment by vorg** [comment]
As package.json points to dist folder how do we safeguard ourself from fixing a bug, bumping a version, pushing to npm just to discover we forgot to build in the meantime..

- [ ] propose publishing process

**Comment by dmnsgn** [comment]
*Build*
The build config is in one place: https://github.com/pex-gl/pex-renderer/blob/35054ea8c2009b900299ab1a562fff075b744c9d/rollup.config.js

*`debug` issue*
They just haven't published to npm but the version on GH works

* basic-mjs example
Simply adding babelify as a transform to budo should work. pex-context will be processed normally.

* ensure build is published
We can add a `prepublishOnly` in the package.json with "npm run build"

**Comment by vorg** [comment]
@dmnsgn Create issue for remining taks and lets merge this

**Comment by vorg** [comment]
With build modules like that any suggestions for a watch script for developing examples? So we can test new feature with an example without running `build` manually all the time?

**Comment by vorg** [comment]
We will not follow on this one currently as it adds too much complexity with unclear benefits.

**Pull request closed without merging**
