### PR TITLE
feat: add ktx and basis loaders for gltf support

### PR DESCRIPTION
**Pull request by dmnsgn**
- [ ] options.basisOptions should be opts.basisOptions

### CODE REVIEW

**Comment by dmnsgn** [comment]
https://github.com/pex-gl/pex-renderer/pull/290/files?file-filters%5B%5D=.bin&file-filters%5B%5D=.glb&file-filters%5B%5D=.gltf&file-filters%5B%5D=.js&file-filters%5B%5D=.ktx2&file-filters%5B%5D=.wasm#diff-87811566cf44cfa2530f48a396c80080b6a5ea307a282e8dd1e8c55172f40299R202-R208

I should check for array of TypedArray instead of just `.compressed` (basis loader can return uncompressed fallback mipmaps).

**Comment by vorg** [comment]
- [ ] we have an issue with `getPexMaterialTexture` crashing when trying to resize NPOT of image as texture is having mipmaps but the source data is compressed blob not html image source. Disabling check prevents the crash but leads to GL errors as now we are trying to upload NPOT mipmaps which webgl1 doesn't support.

**Comment by dmnsgn** [comment]
- [ ] options.basisOptions should be opts.basisOptions

**Comment by dmnsgn** [comment]
Closing as included in pex-loaders + pex-renderer gltf ([issue about leftovers here if needed](https://github.com/pex-gl/pex-loaders/issues/2))

**Pull request closed without merging**
